language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6.1
  # Specify jruby versions until rvm/rvm#4210 are resolved
  - jruby-9.1.9.0
  - jruby-9.1.10.0

before_install:
  - "gem install bundler"

jobs:
  include:
    - stage: spec:live
      rvm: 2.3
      script: bundle exec rake clean_live set_travis_credentials spec:live

script:
  - bundle exec rake
  - bundle exec rubocop

branches:
  only: master

sudo: false
