language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - jruby

install:
  - "gem install bundler"
  - "bundle install --jobs=3 --retry=3"

script:
  - bundle exec rake
  - bundle exec rubocop

branches:
  only: master

sudo: false
